independent_variables:
- header: {name: 'centrality'}
  values:
  - {low: 0, high: 5}
  - {low: 5, high: 10}
  - {low: 10, high: 15}
  - {low: 15, high: 20}
  - {low: 20, high: 30}
  - {low: 30, high: 40}
  - {low: 40, high: 50}
  - {low: 50, high: 60}
  - {low: 60, high: 70}
  - {low: 70, high: 80}
  - {low: 80, high: 92}
dependent_variables:
- header: {name: '$N_{Part}$'}
  values:
  - value: 351.4
  - value: 299.0
  - value: 253.9
  - value: 215.3
  - value: 166.6
  - value: 114.2
  - value: 74.4
  - value: 45.5
  - value: 25.7
  - value: 13.4
  - value: 6.3
- header: {name: '$N_{Coll}$'}
  values:
  - value: 1065
  - value: 854.4
  - value: 672.4
  - value: 532.7
  - value: 373.8
  - value: 219.8
  - value: 120.3
  - value: 61.0
  - value: 28.5
  - value: 12.4
  - value: 4.9
